server:
  port: 8081
spring:
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.xml
  datasource:
#    external data source
    eshop:
      username: "postgres"
      password: "root"
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/eshop
#      primary data source
    eshop-orders:
      username: "postgres"
      password: "root"
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/eshop_orders
  jpa:
    hibernate:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
